### PR TITLE
Bump version, new line length

### PR DESCRIPTION
**Pull request by mdelaossa**
Could we publish a new version to take advantage of the new extended line length rule in rubocop?

### CODE REVIEW

**Review by robertfairhead — APPROVED** [review]
makeitso

**Comment by mdelaossa** [comment]
@robertfairhead can you also publish the new gem version while you're at it please? :P

**Comment by robertfairhead** [comment]
I don't have access. It looks like only Frank does https://rubygems.org/gems/aptible-tasks

You can ask him to give you access to it so you can publish it going forward

**Comment by mdelaossa** [comment]
Ah! Sorry, I thought I had seen you listed as owner along with @fancyremarker. I'll reach out to him if he doesn't notice this message :)

**Pull request merged**
